# csv

## A CSV (Comma-Separated Values) file is a plain text format used to store tabular data where each line represents a row and values are separated by a delimiter, typically a comma. It is widely supported by spreadsheet tools, databases, and programming languages, making it a universal choice for data exchange.

### Key characteristics include:

#### Delimiters: Commonly commas, but can also be semicolons, tabs, or pipes.

#### Quotes: Used to wrap values containing delimiters or special characters.

#### Header rows: Optional first row describing column names.

## TSV (Tab-Separated Values) file, a simple, plain-text format that organizes information in rows and columns using tabs as separators. TSV files are easy to read, highly compatible across tools, and ideal for clean, error-free data handling.

In [1]:
import pandas as pd
data = pd.read_csv("Indian_Kids_Screen_Time.csv")

In [2]:
data

      Age  Gender  ...                   Health_Impacts Urban_or_Rural
0      14    Male  ...           Poor Sleep, Eye Strain          Urban
1      11  Female  ...                       Poor Sleep          Urban
2      18  Female  ...                       Poor Sleep          Urban
3      15  Female  ...                              NaN          Urban
4      12  Female  ...              Poor Sleep, Anxiety          Urban
...   ...     ...  ...                              ...            ...
9707   17    Male  ...                       Poor Sleep          Urban
9708   17  Female  ...                       Poor Sleep          Rural
9709   16    Male  ...  Poor Sleep, Eye Strain, Anxiety          Rural
9710   17    Male  ...                       Poor Sleep          Urban
9711   15  Female  ...                          Anxiety          Urban

[9712 rows x 8 columns]

In [6]:
# open csv file through url
 
import requests
from io import StringIO


url = "https://raw.githubusercontent.com/datasets/oil-prices/main/data/brent-daily.csv"
response = requests.get(url)
df = pd.read_csv(StringIO(response.text))
print(df.head())

         Date  Price
0  1987-05-20  18.63
1  1987-05-21  18.45
2  1987-05-22  18.55
3  1987-05-25  18.60
4  1987-05-26  18.63

In [8]:
# for tsv file
# data = pd.read_csv('Indian_Kids_Screen_Time.tsv',sep ="/t")

# if no columns names  use names parmeter
# data = pd.read_csv('Indian_Kids_Screen_Time.tsv',sep ="/t",names =["  ","  "])

# parmeter

In [9]:
1 # data = pd.read_csv("Indian_Kids_Screen_Time.csv",index_col =" Column name")
2 # data = pd.read_csv("Indian_Kids_Screen_Time.csv",header =1)
3 # data= pd.read_csv("Indian_Kids_Screen_Time.csv",use_cols=[" "," col names",""])
4 # data = pd.read_csv("Indian_Kids_Screen_Time.csv", usecol=["col name"],squeeze =True)

4

In [10]:
#data = pd.read_csv("Indian_Kids_Screen_Time.csv",nrows=100)
# data = pd.read_csv("Indian_Kids_Screen_Time.csv",encoding ="latin-1")

# Json/SQL

# JSON (JavaScript Object Notation) is a lightweight, text-based format for storing and exchanging structured data. It is human-readable, easy to parse, and supported by almost all modern programming languages, making it a standard for APIs, configuration files, and data transfer between clients and servers.

In [1]:
import pandas as pd

In [3]:
import json

with open("sample.json", "r") as f:
    data = json.load(f)

print(data)

{'labels': {'HAPROXY_0_STICKY': 'true', 'HAPROXY_GROUP': 'external', 'HAPROXY_0_VHOST': 'data.lab.org'}, 'id': '/lab/big-databio', 'backoffFactor': 1.15, 'backoffSeconds': 1, 'constraints': [['@region', 'IS', 'uva-udc']], 'container': {'type': 'MESOS', 'volumes': [{'containerPath': '/usr/share/nginx/html', 'hostPath': '/mnt/qproject/lab/www', 'mode': 'RO'}, {'containerPath': '/var/log/nginx', 'hostPath': '/var/log/nginx', 'mode': 'RW'}], 'portMappings': [{'containerPort': 80, 'hostPort': 0, 'protocol': 'tcp'}], 'docker': {'image': 'databio/nginx-auto:latest', 'forcePullImage': True, 'parameters': []}}, 'cpus': 0.5, 'disk': 0, 'healthChecks': [{'gracePeriodSeconds': 5, 'ignoreHttp1xx': False, 'intervalSeconds': 3, 'maxConsecutiveFailures': 2, 'portIndex': 0, 'timeoutSeconds': 2, 'delaySeconds': 15, 'protocol': 'HTTP', 'path': '/'}], 'instances': 1, 'maxLaunchDelaySeconds': 300, 'mem': 512, 'gpus': 0, 'networks': [{'mode': 'container/bridge'}], 'requirePorts': False, 'upgradeStrategy': {'maximumOverCapacity': 1, 'minimumHealthCapacity': 1}, 'killSelection': 'YOUNGEST_FIRST', 'unreachableStrategy': {'inactiveAfterSeconds': 30, 'expungeAfterSeconds': 0}, 'role': 'shefflab', 'fetch': []}

In [5]:
df = pd.json_normalize(data)
print(df.head())

                 id  backoffFactor  backoffSeconds               constraints  \
0  /lab/big-databio           1.15               1  [[@region, IS, uva-udc]]

   cpus  disk                                       healthChecks  instances  \
0   0.5     0  [{'gracePeriodSeconds': 5, 'ignoreHttp1xx': Fa...          1

   maxLaunchDelaySeconds  mem  ...  container.type  \
0                    300  512  ...           MESOS

                                   container.volumes  \
0  [{'containerPath': '/usr/share/nginx/html', 'h...

                              container.portMappings  \
0  [{'containerPort': 80, 'hostPort': 0, 'protoco...

      container.docker.image container.docker.forcePullImage  \
0  databio/nginx-auto:latest                            True

  container.docker.parameters upgradeStrategy.maximumOverCapacity  \
0                          []                                   1

  upgradeStrategy.minimumHealthCapacity  \
0                                     1

  unreachableStrategy.inactiveAfterSeconds  \
0                                       30

  unreachableStrategy.expungeAfterSeconds
0                                       0

[1 rows x 29 columns]

In [7]:
df.head(20)

,id,backoffFactor,backoffSeconds,constraints,cpus,disk,healthChecks,instances,maxLaunchDelaySeconds,mem,...,container.type,container.volumes,container.portMappings,container.docker.image,container.docker.forcePullImage,container.docker.parameters,upgradeStrategy.maximumOverCapacity,upgradeStrategy.minimumHealthCapacity,unreachableStrategy.inactiveAfterSeconds,unreachableStrategy.expungeAfterSeconds
0,/lab/big-databio,1.15,1,"[[@region, IS, uva-udc]]",0.5,0,"[{'gracePeriodSeconds': 5, 'ignoreHttp1xx': Fa...",1,300,512,...,MESOS,"[{'containerPath': '/usr/share/nginx/html', 'h...","[{'containerPort': 80, 'hostPort': 0, 'protoco...",databio/nginx-auto:latest,True,[],1,1,30,0

In [8]:
pd.read_json("https://api.exchangerate-api.com/v4/latest/INR")

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.0384
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.6590
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.8640
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,3.8600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.1720
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.1850
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.2800
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-09,1780963201,0.2800

# API

In [9]:
import requests

In [23]:
import requests

url = "https://linkedin-job-search-api.p.rapidapi.com/active-jb-7d"


headers = {
    "x-rapidapi-key": "ec429feb5cmsh68e227613cff6e5p1e0114jsn30539bdc1e32",
    "x-rapidapi-host": "linkedin-job-search-api.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.json())

200

In [24]:
data = response.json()

df = pd.json_normalize(data)

print(df.head())

           id              date_posted                date_created  \
0  2197109623  2026-06-09T23:32:52.397  2026-06-09T23:32:52.452571
1  2197109488      2026-06-09T23:32:35  2026-06-09T23:32:43.717972
2  2197110052      2026-06-09T23:32:20  2026-06-09T23:33:16.843634
3  2197110061      2026-06-09T23:32:20  2026-06-09T23:33:17.398569
4  2197109284      2026-06-09T23:31:37  2026-06-09T23:32:28.089037

                                     title  \
0                    Livestock Underwriter
1                 Business Systems Manager
2       Maintenance Tech II - Nights 2/2/3
3         Maintenance Tech II - Days 2/2/3
4  Lead - Strategic Inventory Distribution

                                        organization  \
0                                            Palomar
1                                             TriNet
2                                      Michael Foods
3                                      Michael Foods
4  Sonny's Enterprises Inc. - Conveyorized Car Wa...

                                    organization_url    date_validthrough  \
0     https://www.linkedin.com/company/plmrinsurance                 None
1            https://www.linkedin.com/company/trinet  2026-07-09T23:32:35
2     https://www.linkedin.com/company/michael-foods  2026-07-09T23:32:20
3     https://www.linkedin.com/company/michael-foods  2026-07-09T23:32:20
4  https://www.linkedin.com/company/sonny's-enter...  2026-07-09T23:31:37

                                       locations_raw location_type  \
0  [{'@type': 'Place', 'address': {'@type': 'Post...          None
1  [{'@type': 'Place', 'address': {'@type': 'Post...          None
2  [{'@type': 'Place', 'address': {'@type': 'Post...          None
3  [{'@type': 'Place', 'address': {'@type': 'Post...          None
4  [{'@type': 'Place', 'address': {'@type': 'Post...          None

  location_requirements_raw  ...  no_jb_schema external_apply_url  \
0                      None  ...          True               None
1                      None  ...          None               None
2                      None  ...          None               None
3                      None  ...          None               None
4                      None  ...          None               None

  ats_duplicate linkedin_id salary_raw.@type salary_raw.currency  \
0          True  4426016211              NaN                 NaN
1          True  4426545698              NaN                 NaN
2          True  4426545696              NaN                 NaN
3          True  4426564560              NaN                 NaN
4         False  4426551681              NaN                 NaN

  salary_raw.value.@type salary_raw.value.minValue salary_raw.value.maxValue  \
0                    NaN                       NaN                       NaN
1                    NaN                       NaN                       NaN
2                    NaN                       NaN                       NaN
3                    NaN                       NaN                       NaN
4                    NaN                       NaN                       NaN

  salary_raw.value.unitText
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN

[5 rows x 52 columns]

In [25]:
df

,id,date_posted,date_created,title,organization,organization_url,date_validthrough,locations_raw,location_type,location_requirements_raw,...,no_jb_schema,external_apply_url,ats_duplicate,linkedin_id,salary_raw.@type,salary_raw.currency,salary_raw.value.@type,salary_raw.value.minValue,salary_raw.value.maxValue,salary_raw.value.unitText
0,2197109623,2026-06-09T23:32:52.397,2026-06-09T23:32:52.452571,Livestock Underwriter,Palomar,https://www.linkedin.com/company/plmrinsurance,None,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,True,None,True,4426016211,NaN,NaN,NaN,NaN,NaN,NaN
1,2197109488,2026-06-09T23:32:35,2026-06-09T23:32:43.717972,Business Systems Manager,TriNet,https://www.linkedin.com/company/trinet,2026-07-09T23:32:35,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,True,4426545698,NaN,NaN,NaN,NaN,NaN,NaN
2,2197110052,2026-06-09T23:32:20,2026-06-09T23:33:16.843634,Maintenance Tech II - Nights 2/2/3,Michael Foods,https://www.linkedin.com/company/michael-foods,2026-07-09T23:32:20,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,True,4426545696,NaN,NaN,NaN,NaN,NaN,NaN
3,2197110061,2026-06-09T23:32:20,2026-06-09T23:33:17.398569,Maintenance Tech II - Days 2/2/3,Michael Foods,https://www.linkedin.com/company/michael-foods,2026-07-09T23:32:20,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,True,4426564560,NaN,NaN,NaN,NaN,NaN,NaN
4,2197109284,2026-06-09T23:31:37,2026-06-09T23:32:28.089037,Lead - Strategic Inventory Distribution,Sonny's Enterprises Inc. - Conveyorized Car Wa...,https://www.linkedin.com/company/sonny's-enter...,2026-07-09T23:31:37,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,False,4426551681,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2197109579,2026-06-09T23:28:36,2026-06-09T23:32:49.538398,Patient Access Rep [210535],Aquent,https://www.linkedin.com/company/aquent,2026-07-09T23:28:36,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,None,4426552630,MonetaryAmount,USD,QuantitativeValue,42.09,45.16,HOUR
96,2197109722,2026-06-09T23:28:36,2026-06-09T23:32:58.506909,Administrative Assistant [210706],Aquent,https://www.linkedin.com/company/aquent,2026-07-09T23:28:36,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,None,4426561586,MonetaryAmount,USD,QuantitativeValue,22.00,24.00,HOUR
97,2197109895,2026-06-09T23:28:36,2026-06-09T23:33:09.26058,UX Designer (III) [210707],Aquent,https://www.linkedin.com/company/aquent,2026-07-09T23:28:36,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,None,4426553650,MonetaryAmount,USD,QuantitativeValue,98.63,111.00,HOUR
98,2197109944,2026-06-09T23:28:35,2026-06-09T23:33:12.01619,Behavior Technician,Applied ABC,https://www.linkedin.com/company/applied-abc,2026-07-09T23:28:35,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,False,4426019199,MonetaryAmount,USD,QuantitativeValue,20.00,30.00,HOUR
99,2197110169,2026-06-09T23:28:34,2026-06-09T23:33:21.795057,QA/SDC/IP Nurse,Shalom Gardens,https://www.linkedin.com/company/shalom-gardens,2026-07-09T23:28:34,"[{'@type': 'Place', 'address': {'@type': 'Post...",None,None,...,None,None,False,4426014257,MonetaryAmount,USD,QuantitativeValue,103064.00,103064.00,YEAR