In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("Indian_Kids_Screen_Time.csv")

In [4]:
# how big is data

In [5]:
data.shape

(9712, 8)

In [6]:
# how does the data look like

In [7]:
data.head(5)

   Age  Gender  Avg_Daily_Screen_Time_hr  ... Educational_to_Recreational_Ratio          Health_Impacts  Urban_or_Rural
0   14    Male                      3.99  ...                              0.42  Poor Sleep, Eye Strain           Urban
1   11  Female                      4.61  ...                              0.30              Poor Sleep           Urban
2   18  Female                      3.73  ...                              0.32              Poor Sleep           Urban
3   15  Female                      1.21  ...                              0.39                     NaN           Urban
4   12  Female                      5.89  ...                              0.49     Poor Sleep, Anxiety           Urban

[5 rows x 8 columns]

In [8]:
data.sample(7)

      Age  Gender  Avg_Daily_Screen_Time_hr  ... Educational_to_Recreational_Ratio            Health_Impacts  Urban_or_Rural
8834   12    Male                      5.86  ...                              0.47                Poor Sleep           Urban
9420   13  Female                      5.93  ...                              0.41                Eye Strain           Urban
1928   13  Female                      6.89  ...                              0.46                Poor Sleep           Rural
2873    9    Male                      4.72  ...                              0.44  Poor Sleep, Obesity Risk           Urban
4395   17  Female                      4.23  ...                              0.38                       NaN           Rural
7760   17  Female                      8.26  ...                              0.45       Poor Sleep, Anxiety           Urban
1875   17    Male                      4.60  ...                              0.30  Poor Sleep, Obesity Risk           Rural

[7 rows x 8 columns]

In [9]:
# what is data types of col

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

In [11]:
# are there missing vales?

In [12]:
data.isnull().sum()

Age                                     0
Gender                                  0
Avg_Daily_Screen_Time_hr                0
Primary_Device                          0
Exceeded_Recommended_Limit              0
Educational_to_Recreational_Ratio       0
Health_Impacts                       3218
Urban_or_Rural                          0
dtype: int64

In [13]:
# does the data look like mathematicaly

In [14]:
data.describe()

               Age  Avg_Daily_Screen_Time_hr  Educational_to_Recreational_Ratio
count  9712.000000               9712.000000                        9712.000000
mean     12.979201                  4.352837                           0.427226
std       3.162437                  1.718232                           0.073221
min       8.000000                  0.000000                           0.300000
25%      10.000000                  3.410000                           0.370000
50%      13.000000                  4.440000                           0.430000
75%      16.000000                  5.380000                           0.480000
max      18.000000                 13.890000                           0.600000

In [15]:
# are any duplicate values

In [16]:
data.duplicated().sum()

44

In [17]:
data.drop_duplicates()

      Age  Gender  ...                   Health_Impacts Urban_or_Rural
0      14    Male  ...           Poor Sleep, Eye Strain          Urban
1      11  Female  ...                       Poor Sleep          Urban
2      18  Female  ...                       Poor Sleep          Urban
3      15  Female  ...                              NaN          Urban
4      12  Female  ...              Poor Sleep, Anxiety          Urban
...   ...     ...  ...                              ...            ...
9707   17    Male  ...                       Poor Sleep          Urban
9708   17  Female  ...                       Poor Sleep          Rural
9709   16    Male  ...  Poor Sleep, Eye Strain, Anxiety          Rural
9710   17    Male  ...                       Poor Sleep          Urban
9711   15  Female  ...                          Anxiety          Urban

[9668 rows x 8 columns]

In [18]:
# how is the corelation between col

In [25]:
data.corr(numeric_only=True)["Avg_Daily_Screen_Time_hr"]

Age                                  0.118328
Avg_Daily_Screen_Time_hr             1.000000
Exceeded_Recommended_Limit           0.664950
Educational_to_Recreational_Ratio   -0.087552
Name: Avg_Daily_Screen_Time_hr, dtype: float64

In [26]:
data.corr(numeric_only=True)["Avg_Daily_Screen_Time_hr"].sort_values(ascending=False)

Avg_Daily_Screen_Time_hr             1.000000
Exceeded_Recommended_Limit           0.664950
Age                                  0.118328
Educational_to_Recreational_Ratio   -0.087552
Name: Avg_Daily_Screen_Time_hr, dtype: float64

In [27]:
corr_matrix = data.corr(numeric_only=True)
print(corr_matrix)

                                        Age  ...  Educational_to_Recreational_Ratio
Age                                1.000000  ...                          -0.488617
Avg_Daily_Screen_Time_hr           0.118328  ...                          -0.087552
Exceeded_Recommended_Limit         0.159173  ...                          -0.126643
Educational_to_Recreational_Ratio -0.488617  ...                           1.000000

[4 rows x 4 columns]

In [28]:
data.corr(numeric_only=True)

                                        Age  ...  Educational_to_Recreational_Ratio
Age                                1.000000  ...                          -0.488617
Avg_Daily_Screen_Time_hr           0.118328  ...                          -0.087552
Exceeded_Recommended_Limit         0.159173  ...                          -0.126643
Educational_to_Recreational_Ratio -0.488617  ...                           1.000000

[4 rows x 4 columns]